---
apiVersion: console/v2
kind: KafkaCluster
metadata:
  name: partner-gateway
spec:
  displayName: Conduktor Gateway
  icon: meteor
  color: "#00ff00"
  bootstrapServers: conduktor-gateway-passthrough.sni-demo.local:6969
  ignoreUntrustedCertificate: false
  properties:
    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${GATEWAY_ADMIN_TOKEN}";
    security.protocol: SASL_SSL
    sasl.mechanism: PLAIN
    ssl.truststore.location: /security/kafka.conduktor-gateway-passthrough.sni-demo.local.truststore.jks
    ssl.truststore.password: conduktor
  # schemaRegistry:
  #   type: "ConfluentLike"
  #   url: http://schemaregistry:8085
  #   security:
  #     type: BasicAuth
  #     username: admin-sr
  #     password: secret
  #   ignoreUntrustedCertificate: false
  kafkaFlavor:
    type: Gateway
    url: http://conduktor-gateway-passthrough.sni-demo.local:8888
    user: admin
    password: conduktor
    virtualCluster: passthrough