---
apiVersion: gateway/v2
kind: Interceptor
metadata:
  name: guard-on-create-topic
spec:
  pluginClass: "io.conduktor.gateway.interceptor.safeguard.CreateTopicPolicyPlugin"
  priority: 100
  config:
    topic: ".*"
    numPartition:
      min: 1
      max: 3
      action: BLOCK
    replicationFactor:
      min: 3
      max: 3
      action: OVERRIDE
      overrideValue: 3
