---
apiVersion: gateway/v2
kind: VirtualCluster
metadata:
 name: virtual-cluster
spec: {}
---
apiVersion: gateway/v2
kind: GatewayServiceAccount
metadata:
  name: app
  vCluster: virtual-cluster
spec:
  type: LOCAL