apiVersion: "v1"
kind: "TopicPolicy"
metadata:
  name: website-analytics-naming-topic-policy
spec:
  policies:
    metadata.name:
      constraint: Match
      pattern: ^website-analytics\.[a-z0-9.-]+$ # must start with website-analytics.
